### ISSUE TITLE
Lamps don't dim

### ISSUE THREAD

**Issue by 98creep98** [johntelforduk/gpt-hue#1]
I have the problem that lamps can be switched off and on, but if I want to dim them or change the color, it doesn't work.

ChatGPT: PUT/lights/Hue color lamp 1/state {"on": true, "bri": 127, "transitiontime": 300}
Turned on Hue color lamp 1

in this case the light should be dimmed to 50%. Instead, the light just turned off. It's probably not a problem with the script, but I just can't get it to work.

**Comment by johntelforduk** [comment]
I've refactored the program to use the new function calling feature of GPT. This means that I was able to add dimming as a capabaility of the program.
